Fix geo bloom filter crash issue
world-federation-of-advertisers/cardinality_estimation_evaluation_framework pull request #72
Opened 2020-09-21 16:42 UTC by my2457

As noise is added, sometimes, first_moment(lower_bound) >0 can crash the program

2020-09-21 19:36 UTC, jiayu-google approved these changes

2020-09-21 19:36 UTC, kungfucraig approved these changes

2020-09-21 19:37 UTC, kungfucraig requested changes
Can you add a test for this?

2020-09-23 00:06 UTC, huangxichen1 approved these changes
Thank you, Miao!

2020-09-24 23:03 UTC, my2457 commented
> Can you add a test for this?

Test has been added, please take a look, thanks!

2020-09-25 15:04 UTC, kungfucraig approved these changes

2020-09-28 14:31 UTC, merged