Evgskv/colab example
world-federation-of-advertisers/cardinality_estimation_evaluation_framework pull request #93
Opened 2020-10-14 20:05 UTC by EvgSkv

1. Adding CoLab with installation of the framework.
2. Fining a warning in LiquidLegions.

2020-10-14 20:20 UTC, huangxichen1 approved these changes
Thanks, Evgeny!

2020-10-14 23:21 UTC, kungfucraig requested changes

2020-10-14 23:21 UTC, kungfucraig commented on src/estimators/liquid_legions.py
> +      if t == 0:
This should be in a different change.

2020-10-15 01:20 UTC, EvgSkv commented on src/estimators/liquid_legions.py
> +      if t == 0:
Done.

2020-10-15 01:30 UTC, kungfucraig approved these changes

2020-10-15 01:31 UTC, EvgSkv commented
The scope was changed just to add documentation.

2020-10-15 01:32 UTC, merged